// File generated by FlutterFire CLI.
// ignore_for_file: type=lint
import 'package:firebase_core/firebase_core.dart' show FirebaseOptions;
import 'package:flutter/foundation.dart'
    show defaultTargetPlatform, kIsWeb, TargetPlatform;

/// Default [FirebaseOptions] for use with your Firebase apps.
///
/// Example:
/// ```dart
/// import 'firebase_options.dart';
/// // ...
/// await Firebase.initializeApp(
///   options: DefaultFirebaseOptions.currentPlatform,
/// );
/// ```
class DefaultFirebaseOptions {
  static FirebaseOptions get currentPlatform {
    if (kIsWeb) {
      return web;
    }
    switch (defaultTargetPlatform) {
      case TargetPlatform.android:
        return android;
      case TargetPlatform.iOS:
        return ios;
      case TargetPlatform.macOS:
        return macos;
      case TargetPlatform.windows:
        return windows;
      case TargetPlatform.linux:
        throw UnsupportedError(
          'DefaultFirebaseOptions have not been configured for linux - '
              'you can reconfigure this by running the FlutterFire CLI again.',
        );
      default:
        throw UnsupportedError(
          'DefaultFirebaseOptions are not supported for this platform.',
        );
    }
  }

  static const FirebaseOptions web = FirebaseOptions(
    apiKey: 'AIzaSyDrXqVgijcRn2RhyOaqTKH90M1-uJIFCCE',
    appId: '1:222619190569:web:54417cecdea19300356338',
    messagingSenderId: '222619190569',
    projectId: 'backupspark-16ccb',
    authDomain: 'backupspark-16ccb.firebaseapp.com',
    storageBucket: 'backupspark-16ccb.firebasestorage.app',
    measurementId: 'G-PY9K2Q0M5Y',
  );

  static const FirebaseOptions android = FirebaseOptions(
    apiKey: 'AIzaSyA0TBWZVb_lCMXWGDT1BRPQggSYwrZzE6E',
    appId: '1:222619190569:android:e8af574e1160ae0f356338',
    messagingSenderId: '222619190569',
    projectId: 'backupspark-16ccb',
    storageBucket: 'backupspark-16ccb.firebasestorage.app',
  );

  static const FirebaseOptions ios = FirebaseOptions(
    apiKey: 'AIzaSyAyJj7RCVeSzX1U4aqVZwZgopH5K0ogdPU',
    appId: '1:222619190569:ios:13c147f08adb64ae356338',
    messagingSenderId: '222619190569',
    projectId: 'backupspark-16ccb',
    storageBucket: 'backupspark-16ccb.firebasestorage.app',
    iosBundleId: 'com.example.yourProjectName',
  );

  static const FirebaseOptions macos = FirebaseOptions(
    apiKey: 'AIzaSyAyJj7RCVeSzX1U4aqVZwZgopH5K0ogdPU',
    appId: '1:222619190569:ios:13c147f08adb64ae356338',
    messagingSenderId: '222619190569',
    projectId: 'backupspark-16ccb',
    storageBucket: 'backupspark-16ccb.firebasestorage.app',
    iosBundleId: 'com.example.yourProjectName',
  );

  static const FirebaseOptions windows = FirebaseOptions(
    apiKey: 'AIzaSyDrXqVgijcRn2RhyOaqTKH90M1-uJIFCCE',
    appId: '1:222619190569:web:d65cf05d3516e316356338',
    messagingSenderId: '222619190569',
    projectId: 'backupspark-16ccb',
    authDomain: 'backupspark-16ccb.firebaseapp.com',
    storageBucket: 'backupspark-16ccb.firebasestorage.app',
    measurementId: 'G-3KE7DWM410',
  );

}